/** This file was auto generated by ./build/generate-builtin-types.js **/
module.exports = {
    /** OID: 16 (boolean) */
    'BOOL': '',
    /** OID: 17 (bytea) */
    'BYTEA': '',
    /** OID: 18 ("char") */
    'CHAR': '',
    /** OID: 20 (bigint) */
    'INT8': '',
    /** OID: 21 (smallint) */
    'INT2': '',
    /** OID: 23 (integer) */
    'INT4': '',
    /** OID: 24 (regproc) */
    'REGPROC': '',
    /** OID: 25 (text) */
    'TEXT': '',
    /** OID: 26 (oid) */
    'OID': '',
    /** OID: 27 (tid) */
    'TID': '',
    /** OID: 28 (xid) */
    'XID': '',
    /** OID: 29 (cid) */
    'CID': '',
    /** OID: 114 (json) */
    'JSON': '',
    /** OID: 142 (xml) */
    'XML': '',
    /** OID: 194 (pg_node_tree) */
    'PG_NODE_TREE': '',
    /** OID: 602 (path) */
    'PATH': '',
    /** OID: 604 (polygon) */
    'POLYGON': '',
    /** OID: 650 (cidr) */
    'CIDR': '',
    /** OID: 700 (real) */
    'FLOAT4': '',
    /** OID: 701 (double precision) */
    'FLOAT8': '',
    /** OID: 718 (circle) */
    'CIRCLE': '',
    /** OID: 774 (macaddr8) */
    'MACADDR8': '',
    /** OID: 790 (money) */
    'MONEY': '',
    /** OID: 829 (macaddr) */
    'MACADDR': '',
    /** OID: 869 (inet) */
    'INET': '',
    /** OID: 1033 (aclitem) */
    'ACLITEM': '',
    /** OID: 1042 (character) */
    'BPCHAR': '',
    /** OID: 1043 (character varying) */
    'VARCHAR': '',
    /** OID: 1082 (date) */
    'DATE': '',
    /** OID: 1083 (time without time zone) */
    'TIME': '',
    /** OID: 1114 (timestamp without time zone) */
    'TIMESTAMP': '',
    /** OID: 1184 (timestamp with time zone) */
    'TIMESTAMPTZ': '',
    /** OID: 1186 (interval) */
    'INTERVAL': '',
    /** OID: 1266 (time with time zone) */
    'TIMETZ': '',
    /** OID: 1560 (bit) */
    'BIT': '',
    /** OID: 1562 (bit varying) */
    'VARBIT': '',
    /** OID: 1700 (numeric) */
    'NUMERIC': '',
    /** OID: 1790 (refcursor) */
    'REFCURSOR': '',
    /** OID: 2202 (regprocedure) */
    'REGPROCEDURE': '',
    /** OID: 2203 (regoper) */
    'REGOPER': '',
    /** OID: 2204 (regoperator) */
    'REGOPERATOR': '',
    /** OID: 2205 (regclass) */
    'REGCLASS': '',
    /** OID: 2206 (regtype) */
    'REGTYPE': '',
    /** OID: 2950 (uuid) */
    'UUID': '',
    /** OID: 2970 (txid_snapshot) */
    'TXID_SNAPSHOT': '',
    /** OID: 3220 (pg_lsn) */
    'PG_LSN': '',
    /** OID: 3361 (pg_ndistinct) */
    'PG_NDISTINCT': '',
    /** OID: 3402 (pg_dependencies) */
    'PG_DEPENDENCIES': '',
    /** OID: 3614 (tsvector) */
    'TSVECTOR': '',
    /** OID: 3615 (tsquery) */
    'TSQUERY': '',
    /** OID: 3642 (gtsvector) */
    'GTSVECTOR': '',
    /** OID: 3734 (regconfig) */
    'REGCONFIG': '',
    /** OID: 3769 (regdictionary) */
    'REGDICTIONARY': '',
    /** OID: 3802 (jsonb) */
    'JSONB': '',
    /** OID: 4072 (jsonpath) */
    'JSONPATH': '',
    /** OID: 4089 (regnamespace) */
    'REGNAMESPACE': '',
    /** OID: 4096 (regrole) */
    'REGROLE': '',
    /** OID: 5017 (pg_mcv_list) */
    'PG_MCV_LIST': '',
    /** OID: 1000 (boolean[]) */
    '_BOOL': '',
    /** OID: 1001 (bytea[]) */
    '_BYTEA': '',
    /** OID: 1002 ("char"[]) */
    '_CHAR': '',
    /** OID: 1016 (bigint[]) */
    '_INT8': '',
    /** OID: 1005 (smallint[]) */
    '_INT2': '',
    /** OID: 1007 (integer[]) */
    '_INT4': '',
    /** OID: 1008 (regproc[]) */
    '_REGPROC': '',
    /** OID: 1009 (text[]) */
    '_TEXT': '',
    /** OID: 1028 (oid[]) */
    '_OID': '',
    /** OID: 1010 (tid[]) */
    '_TID': '',
    /** OID: 1011 (xid[]) */
    '_XID': '',
    /** OID: 1012 (cid[]) */
    '_CID': '',
    /** OID: 199 (json[]) */
    '_JSON': '',
    /** OID: 143 (xml[]) */
    '_XML': '',
    /** OID: 1019 (path[]) */
    '_PATH': '',
    /** OID: 1027 (polygon[]) */
    '_POLYGON': '',
    /** OID: 651 (cidr[]) */
    '_CIDR': '',
    /** OID: 1021 (real[]) */
    '_FLOAT4': '',
    /** OID: 1022 (double precision[]) */
    '_FLOAT8': '',
    /** OID: 719 (circle[]) */
    '_CIRCLE': '',
    /** OID: 775 (macaddr8[]) */
    '_MACADDR8': '',
    /** OID: 791 (money[]) */
    '_MONEY': '',
    /** OID: 1040 (macaddr[]) */
    '_MACADDR': '',
    /** OID: 1041 (inet[]) */
    '_INET': '',
    /** OID: 1034 (aclitem[]) */
    '_ACLITEM': '',
    /** OID: 1014 (character[]) */
    '_BPCHAR': '',
    /** OID: 1015 (character varying[]) */
    '_VARCHAR': '',
    /** OID: 1182 (date[]) */
    '_DATE': '',
    /** OID: 1183 (time without time zone[]) */
    '_TIME': '',
    /** OID: 1115 (timestamp without time zone[]) */
    '_TIMESTAMP': '',
    /** OID: 1185 (timestamp with time zone[]) */
    '_TIMESTAMPTZ': '',
    /** OID: 1187 (interval[]) */
    '_INTERVAL': '',
    /** OID: 1270 (time with time zone[]) */
    '_TIMETZ': '',
    /** OID: 1561 (bit[]) */
    '_BIT': '',
    /** OID: 1563 (bit varying[]) */
    '_VARBIT': '',
    /** OID: 1231 (numeric[]) */
    '_NUMERIC': '',
    /** OID: 2201 (refcursor[]) */
    '_REFCURSOR': '',
    /** OID: 2207 (regprocedure[]) */
    '_REGPROCEDURE': '',
    /** OID: 2208 (regoper[]) */
    '_REGOPER': '',
    /** OID: 2209 (regoperator[]) */
    '_REGOPERATOR': '',
    /** OID: 2210 (regclass[]) */
    '_REGCLASS': '',
    /** OID: 2211 (regtype[]) */
    '_REGTYPE': '',
    /** OID: 2951 (uuid[]) */
    '_UUID': '',
    /** OID: 2949 (txid_snapshot[]) */
    '_TXID_SNAPSHOT': '',
    /** OID: 3221 (pg_lsn[]) */
    '_PG_LSN': '',
    /** OID: 3643 (tsvector[]) */
    '_TSVECTOR': '',
    /** OID: 3645 (tsquery[]) */
    '_TSQUERY': '',
    /** OID: 3644 (gtsvector[]) */
    '_GTSVECTOR': '',
    /** OID: 3735 (regconfig[]) */
    '_REGCONFIG': '',
    /** OID: 3770 (regdictionary[]) */
    '_REGDICTIONARY': '',
    /** OID: 3807 (jsonb[]) */
    '_JSONB': '',
    /** OID: 4073 (jsonpath[]) */
    '_JSONPATH': '',
    /** OID: 4090 (regnamespace[]) */
    '_REGNAMESPACE': '',
    /** OID: 4097 (regrole[]) */
    '_REGROLE': ''
};